Breaking changes due to Feature 2.0 work
* Make `async:true` the default for `invoke` calls (pulumi/pulumi#3750)

* Switch away from native grpc impl. (pulumi/pulumi#3728)

* Remove usage of the 'deasync' library from @pulumi/pulumi. (pulumi/pulumi#3752)

* Only retry as long as we get unavailable back.  Anything else continues. (pulumi/pulumi#3769)

* Handle all errors for now. (pulumi/pulumi#3781)


* Do not assume --yes was present when using pulumi in non-interactive mode (pulumi/pulumi#3793)

* Upgrade all paths for sdk and pkg to v2

* Backport C# invoke classes and other recent gen changes (pulumi/pulumi#4288)

Adjust C# generation

* Replace IDeployment with a sealed class (pulumi/pulumi#4318)

Replace IDeployment with a sealed class

* .NET: default to args subtype rather than Args.Empty (pulumi/pulumi#4320)

* Adding system namespace for Dotnet code gen

This is required for using Obsolute attributes for deprecations

```
Iam/InstanceProfile.cs(142,10): error CS0246: The type or namespace name 'ObsoleteAttribute' could not be found (are you missing a using directive or an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-aws/sdk/dotnet/Pulumi.Aws.csproj]
Iam/InstanceProfile.cs(142,10): error CS0246: The type or namespace name 'Obsolete' could not be found (are you missing a using directive or an assembly reference?) [/Users/stack72/code/go/src/github.com/pulumi/pulumi-aws/sdk/dotnet/Pulumi.Aws.csproj]
```

* Fix the nullability of config type properties in C# codegen (pulumi/pulumi#4379)