[sdk] Support parameterization for remote component resources (#502)
### Description

When generating parameterized .NET SDKs, resources that marked
`isComponent: true` in the schema do not support parameterization
leading to runtime errors that mentioned missing plugins
```
error: Could not automatically download and install resource plugin 'pulumi-resource-<parameterized-package>' at version v0.0.x
```
This PR adds SDK support for parameterized _remote_ component resources.
Still required SDK-gen support from pulumi/pulumi to emit the actual
`RegisterPackageRequest` in the newly added constructor overload

Fixes #503