Skip the new conformance test, it is blocked by a programgen bug
The test currently fails with this error message:

```
=== FAIL: . TestLanguage/l2-resource-option-hide-diffs (21.80s)
    language_test.go:283: l2_resource_option_hide_diffs.go:47:
        	Error Trace:	/home/runner/work/pulumi-dotnet/pulumi-dotnet/pulumi/cmd/pulumi-test-language/tests/l2_resource_option_hide_diffs.go:47
        	            				/home/runner/work/pulumi-dotnet/pulumi-dotnet/pulumi/cmd/pulumi-test-language/interface.go:1435
        	            				/home/runner/work/pulumi-dotnet/pulumi-dotnet/pulumi/cmd/pulumi-test-language/tests/types.go:182
        	            				/opt/hostedtoolcache/go/1.24.7/x64/src/runtime/asm_amd64.s:1700
        	Error:      	Not equal:
        	            	expected: []resource.PropertyPath{resource.PropertyPath{"value"}}
        	            	actual  : []resource.PropertyPath{resource.PropertyPath{"@value"}}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -2,3 +2,3 @@
        	            	  (resource.PropertyPath) (len=1) {
        	            	-  (string) (len=5) "value"
        	            	+  (string) (len=6) "@value"
        	            	  }
```

This shows the value from our checked in code is making it to the engine, so this works
except the programgen bug (https://github.com/pulumi/pulumi/issues/20665).