Fix program codegen for conversions between primitive types (#1116)
While trying to update pulumi-dotnet in pulumi/pulumi, a smoke test
failed https://github.com/pulumi/pulumi/pull/24249

```
Error:
D:\a\_temp\test-env3863622462\out\Rc.cs(29,25): error CS0029: Cannot implicitly convert type 'Pulumi.Output<string>' to 'Pulumi.Output<dynamic>' [D:\a\_temp\test-env3863622462\out\test-env3863622462.csproj]
```

We need to properly handle the IDType in codegen that was introduced in
3.256.0.

Getting `l2-id-type` passing required dealing with primitive
conversions, so that solved a couple other tests along with it.

Int to number conversions now always emit a double literal (`1.0`) when
it's a literal, or a `(double)` cast otherwise, because C#'s
implicitly-typed arrays infer int[] from bare int elements, but that
doesn't convert to `InputList<double>`. Codegen can't tell scalar from
array-element context, so this is always applied, not just in arrays.

I also ran into the issue that we can't have a class called `Invoke`
with a method named `Invoke`. That's now disambiguate with a `Function`
suffix (they are static methods on a static class).