Fix binary compatibility with provider SDKs built using older version of the core SDK (#318)
Fixes #317 

In #311 I introduced a new optional parameter for the constructor of
`ProviderResource` so previously it was:
```cs
public ProviderResource(
            string package,
            string name,
            ResourceArgs args,
            CustomResourceOptions? options = null)
```
and it became:
```cs
public ProviderResource(
    string package,
    string name,
    ResourceArgs args,
    CustomResourceOptions? options = null,
    RegisterPackageRequest? registerPackageRequest = null)
```
Since the parameter is optional, I assumed that it is not a breaking
change. However, when using provider SDKs built with an older version
Pulumi (before v3.66.0) in combination with this new version (v3.66.0)
it gives a _runtime_ error:
```
System.MissingMethodException: Method not found: 'Void Pulumi.ProviderResource..ctor(System.String, System.String, Pulumi.ResourceArgs, Pulumi.CustomResourceOptions)
```
Because the provider SDKs look for that _exact_ constructor signature,
regardless of optionalness.

I was able to repro using the latest `Pulumi.Random` v4.16.3 (built with
`Pulumi` v3.64.0) in combination with `Pulumi` v3.66.0, running this
program (it builds correctly tho)
```cs
var randomProvider = new Random.Provider("random", new Random.ProviderArgs
{
    
});
var pet = new Random.RandomPet("pet", new ()
{
    Length = 12
}, new CustomResourceOptions
{
    Provider = randomProvider
});
```

This PR brings back that constructor signature to fix the problem